### ISSUE TITLE
Pnpm dlx Drizzle Visualizer is failing

### ISSUE THREAD

**Issue by tobychidi** [rphlmr/drizzle-lab#27]
### Error
Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

### Info
My schema folder includes multiple schema files and a barrel file.

**Comment by rphlmr** [comment]
Thanks for reporting. I will try to fix that on windows 😬

**Comment by rphlmr** [comment]
Hello again! Can you retry? `pnpm dlx drizzle-lab@latest visualizer`

For some reason, pnpm keeps a cache if I omit the `@latest`

**Comment by tobychidi** [comment]
@rphlmr  The initial issue has been resolved. 

But more issues: First of all a problem I had with enums I reused in different files. I had to create two different ones. Now, this error:

```

 Warning  We've found duplicated index name across public schema. Please rename your index in either the branches table or the table with the duplicated index name
Error loading snapshot Error
    at file:///C:/Users/tobychidi/AppData/Local/pnpm-cache/dlx/m2ckczhqiz7fqktrcwa7dpecj4/1932f83571c-6e5c/node_modules/.pnpm/drizzle-lab@0.2.1_@remix-run+router@1.21.0_hono@4.6.10_remix-hono@0.0.16_zod@3.23.8__vite@5.4.11/node_modules/drizzle-lab/visualizer/server/assets/index.node-DQNE9H9z.js:2855:17
    at Array.forEach (<anonymous>)
    at drizzleObjectsToSnapshot (file:///C:/Users/tobychidi/AppData/Local/pnpm-cache/dlx/m2ckczhqiz7fqktrcwa7dpecj4/1932f83571c-6e5c/node_modules/.pnpm/drizzle-lab@0.2.1_@remix-run+router@1.21.0_hono@4.6.10_remix-hono@0.0.16_zod@3.23.8__vite@5.4.11/node_modules/drizzle-lab/visualizer/server/assets/index.node-DQNE9H9z.js:2778:13)
    at loader (file:///C:/Users/tobychidi/AppData/Local/pnpm-cache/dlx/m2ckczhqiz7fqktrcwa7dpecj4/1932f83571c-6e5c/node_modules/.pnpm/drizzle-lab@0.2.1_@remix-run+router@1.21.0_hono@4.6.10_remix-hono@0.0.16_zod@3.23.8__vite@5.4.11/node_modules/drizzle-lab/visualizer/server/assets/server-build-D9Dv8Hj-.js:41618:26)
    at async Object.callRouteLoader (C:\Users\tobychidi\AppData\Local\pnpm-cache\dlx\m2ckczhqiz7fqktrcwa7dpecj4\1932f83571c-6e5c\node_modules\.pnpm\@remix-run+server-runtime@2.14.0\node_modules\@remix-run\server-runtime\dist\data.js:59:16)
    at async C:\Users\tobychidi\AppData\Local\pnpm-cache\dlx\m2ckczhqiz7fqktrcwa7dpecj4\1932f83571c-6e5c\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\dist\router.cjs.js:4726:19
    at async callLoaderOrAction (C:\Users\tobychidi\AppData\Local\pnpm-cache\dlx\m2ckczhqiz7fqktrcwa7dpecj4\1932f83571c-6e5c\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\dist\router.cjs.js:4792:16)
    at async Promise.all (index 0)
    at async defaultDataStrategy (C:\Users\tobychidi\AppData\Local\pnpm-cache\dlx\m2ckczhqiz7fqktrcwa7dpecj4\1932f83571c-6e5c\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\dist\router.cjs.js:4651:17)
    at async callDataStrategyImpl (C:\Users\tobychidi\AppData\Local\pnpm-cache\dlx\m2ckczhqiz7fqktrcwa7dpecj4\1932f83571c-6e5c\node_modules\.pnpm\@remix-run+router@1.21.0\node_modules\@remix-run\router\dist\router.cjs.js:4683:17)
    ```
 
I have preffixed all my index names but still. And no specifics on where the conflict is. Also when I run Visualizer it takes a long time for the page to load on the broswer.

**Comment by rphlmr** [comment]
Hey 👋
I have a lot of trouble with Windows and pnpm dlx on all platforms.
It seems that pnpm doesn't work like npx or bunx and for some reason it doesn't properly load files.

Could you check with npx?

For your enum issue, how can I reproduce? Multi schema files and a shared enum?

**Comment by tobychidi** [comment]
> Hey 👋 I have a lot of trouble with Windows and pnpm dlx on all platforms. It seems that pnpm doesn't work like npx or bunx and for some reason it doesn't properly load files.
> 
> Could you check with npx?
> 
> For your enum issue, how can I reproduce? Multi schema files and a shared enum?

For the enum issue. Yes multi schema files + and index.ts barrel file. Import the enum from the barrel in another schema file. I have already sorted the imports.

**Comment by rphlmr** [comment]
would you be able to make/share a little repro? Just a simple thing.

Note: If your barrel exports your schema and the enum, and one of these schemas imports from this barrel, you have a circular dependency.

**Comment by tobychidi** [comment]
I think I know what the problem is. 

```js
export const posts = pgTable(
  "posts",
  {
    id: serial().primaryKey(),
    title: text().notNull(),
    content: text().notNull(),
    authorId: integer()
      .references(() => users.id)
      .notNull(),
    status: statusEnum().default("active").notNull(),
    createdAt: timestamp().defaultNow().notNull(),
    updatedAt: timestamp().defaultNow().notNull(),
  },
  (table) => [
    index("author_idx").on(table.authorId),
    index("post_status_idx").on(table.status),
  ]
);
```

I didnt get the error in the [reproduction](https://github.com/tobychidi/drizzle-lab-reprod) until I removed the column name aliases. Check here: https://github.com/tobychidi/drizzle-lab-reprod

**Comment by alexcroox** [comment]
Getting the same error: 

`Warning  We've found duplicated index name across public schema. Please rename your index in either the app-notification-log table or the table with the duplicated index name`

```
export const notification = pgTable(
  'app-notification-log',
  {
    id: text()
      .primaryKey()
      .$defaultFn(() => generatePrimaryKey('noty')),
    userId: text().references(() => user.id),
    tenantId: text()
      .references(() => tenant.id)
      .notNull(),
    type: text(),
    recipient: text(),
    status: text(),
    contextId: text(),
    data: jsonb(),
    error: text(),
    templateId: text(),
    createdAt: timestamp({ mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
  },
  notification => [
    index().on(
      notification.tenantId,
      notification.userId,
      notification.recipient,
      notification.createdAt,
    ),
  ],
)
```

**Comment by rphlmr** [comment]
Could be linked to https://github.com/drizzle-team/drizzle-orm/issues/3179

Drizzle Lab is a community project based on a drizzle kit fork.
Maybe I'm a little bit late on a fix.

Is it okay with drizzle-kit (migration, push)?

@tobychidi I will look at your repro tomorrow. Thanks for sharing!

**Comment by alexcroox** [comment]
yeah in the past few weeks drizzle updated to allow you not to specify column names as it could infer them from the key. So if you aren't in sync with that I imagine it would cause all sorts of issues if they aren't specified.

**Comment by rphlmr** [comment]
Hello again 👋

I have tested with the latest drizzle-lab version (0.5.0) and I have no error when start `pnpm dlx drizzle-lab@latest visualizer`

**Comment by alexcroox** [comment]
Yeah the error no longer appears thanks. 

I can't fully test as I use aliases in my schema imports so drizzle can't find them.

Currently trying what I do with drizzle-kit generate/migrate (command below). Not having much luck but that's out of the scope of this issue. Just wanted to let you know the previous error was fixed.

`npx tsx --tsconfig ./.nuxt/tsconfig.server.json  /Users/alex/.npm/_npx/ac1053f24966dcd4/node_modules/drizzle-lab/cli.js visualizer`

**Comment by rphlmr** [comment]
I have added an experimental support for typescript alias.
Drizzle lab (and the Drizzle vscode extension).
If it doesn't work well, you can see some debug info with the --debug flag

**Comment by alexcroox** [comment]
Ah I see it picks up the TSX_TS_CONFIG_PATH correctly.

`TSX_TSCONFIG_PATH: '/Users/alex/Projects/saas/tsconfig.json'`

I guess the issue is in Nuxt the tsconfig.json contents are:

```
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json"
}
```

and perhaps it's unable to load/follow the extends. Drizzle kit is the same which is why I run with --tsconfig and point it directly to the extends file where it can read it correctly.

**Comment by tobychidi** [comment]
Thanks @rphlmr for all the work. The issue has indeed been resolved. 

https://github.com/user-attachments/assets/d1f9c643-5ae8-4d8a-8c25-e2999a47f04b

I decided to blur the content. But you see my project has a lot of tables and this is the minimum zoom. 

Hope this helps to point out some adjustments that could be made to layout and zooming.

**Comment by rphlmr** [comment]
> Ah I see it picks up the TSX_TS_CONFIG_PATH correctly.
> 
> 
> 
> `TSX_TSCONFIG_PATH: '/Users/alex/Projects/saas/tsconfig.json'`
> 
> 
> 
> I guess the issue is in Nuxt the tsconfig.json contents are:
> 
> 
> 
> ```
> 
> {
> 
>   // https://nuxt.com/docs/guide/concepts/typescript
> 
>   "extends": "./.nuxt/tsconfig.json"
> 
> }
> 
> ```
> 
> 
> 
> and perhaps it's unable to load/follow the extends. Drizzle kit is the same which is why I run with --tsconfig and point it directly to the extends file where it can read it correctly.
> 
> 

The comment breaks the json parsing. I will try to be more tolerant but parsing is sensitive 😅

TSX_TS_CONFIG_PATH was for tsx, I have migrated to Jiti.

Jiti doesn’t handle tsconfig directly but can resolve path aliases, so I built a parser to extract the path aliases and pass them to Jiti.

**Comment by rphlmr** [comment]
> Thanks @rphlmr for all the work. The issue has indeed been resolved. 
> 
> 
> 
> https://github.com/user-attachments/assets/c7631ced-3fde-4a10-9c64-ea97836ae199
> 
> 
> 
> I had to blur the content. But you see my project has a lot of tables and this is the minimum zoom. 
> 
> 
> 
> Hope this helps to point out some adjustments that could be made to layout and zooming. 

Do you want me to try increasing the max distance?

**Comment by tobychidi** [comment]
Yes. I would like to see more tables at once. And maybe the tables could be a little bit closer together?

**Comment by rphlmr** [comment]
Hey Toby, you should be able to zoom out as much as you want now (vscode extension 0.3.0 and drizzle-lab cli 0.6.0)

**Comment by tobychidi** [comment]
I hate to be a bearer of bad news, but we may have a regression. The error "index" error came up again.

**Comment by rphlmr** [comment]
No problem 🫡 It’s still a preview.
I’ve added a lot of logs in the VS Code output panel and the CLI (with the --debug flag).
If you can share some of them, I’ll take a look tomorrow morning!

**Comment by tobychidi** [comment]
Okay. I'll try it in VSCode. I couldn't find the extension on open-vsx though.

**Comment by rphlmr** [comment]
> Okay. I'll try it in VSCode. I couldn't find the extension on open-vsx though. 

Oh I will look at open vsx. Never heard of it 😬.

**Comment by rphlmr** [comment]
Working on a fix
