### ISSUE TITLE
[Visualizer]: Add alt button on scroll to scroll vertically and horizontally

### ISSUE THREAD

**Issue by Angelelz** [rphlmr/drizzle-lab#29]
Right now scrolling defaults to zoom in and out, which is fine.
It would be great if there could be an button I could hold to allow me to scroll up and down and left to right.
By default the browser scroll horizontally in you hold shift, so I would suggest to use a different key, like command in mac and control in windows, such that by holding it with shift, allows to scroll horizontally.

**Comment by rphlmr** [comment]
Let's try this, like Figma:

default => vertical scroll
shift => horizontal scroll
ctrl or cmd => zoom
