### ISSUE TITLE
[FEATURE]: Schema visualizer to output high resolution screenshot

### ISSUE THREAD

**Issue by chanmathew** [rphlmr/drizzle-lab#35]
### Feature hasn't been suggested before.

- [X] I have verified this feature I'm about to request hasn't been suggested before.

### Describe the enhancement you want to request

Hi there,

Thanks for this great lib! I was testing out the schema visualizer and noticed that by default, the output JPG is only based on the current zoom level you're at, so if you have a lot of tables, the output won't really allow you to zoom in and see all the table details, as once you zoom it's not high resolution enough.

It would be great if by default the output scales to the size of the tables, or at least output a much higher resolution version so you can still zoom in and see all the details.

**Comment by rphlmr** [comment]
👋 Thanks for this request!

You are right, I was struggling myself too. Will look at that asap.

**Comment by rphlmr** [comment]
The new version should fix that 🥳
