### ISSUE TITLE
[BUG]:Not working if the enviroment is imported from .env file

### ISSUE THREAD

**Issue by williamneves** [rphlmr/drizzle-lab#39]
### Report hasn't been filed before.

- [X] I have verified that the bug I'm about to report hasn't been filed before.

### What version of `vscode-drizzle-orm` are you using?

0.6.0

### Are you using Cursor or any other VSCode fork?

- [X] yes

### Is it related to `drizzle.run`?

- [ ] yes

### What version of `drizzle-lab` are you using?

0.6.0

### What version of `@drizzle-lab/api` are you using?

0.6.0

### Describe the Bug

I'm using the t3 stack; by default, they use a .env file in the database environment. 

TVisualizerzer does not work with this setup. 

The workaround is to change for process.env.

If it is impossible to read from .env, we can create another drizzle config just for sforsualizerualizer.

**Comment by rphlmr** [comment]
👋 I will look at that.
I will create a T3 stack and see how it works.

Does it affect only the cli (`npx drizzle-lab visualizer`) or also the vscode plugin? Maybe both?

**Comment by rphlmr** [comment]
👋 It should work now

```sh
npx drizzle-lab@latest visualizer --env-path=.env   
```

In the vscode extension too
